---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: flux-sample-app
  name: flux-sample-app
spec:
  minReadySeconds: 3
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: flux-sample-app
  template:
    metadata:
      labels:
        app: flux-sample-app
    spec:
      containers:
      - name: flux-sample-app
        image: 550945418071.dkr.ecr.eu-west-1.amazonaws.com/flux-sample-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 64Mi
