apiVersion: v1
kind: Service
metadata:
  namespace: flux-sample-app
  name: flux-sample-app
spec:
  type: ClusterIP
  selector:
    app: flux-sample-app
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: http

